# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('due_date', models.DateTimeField(verbose_name='date due')),
            ],
        ),
    ]
